// <auto-generated />
namespace LinkLogger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class UserAndDataContextCombined_Mvc5Rtm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAndDataContextCombined_Mvc5Rtm));
        
        string IMigrationMetadata.Id
        {
            get { return "201311021319265_UserAndDataContextCombined_Mvc5Rtm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
